### ISSUE TITLE
Tensorflow expects a sorted array

### ISSUE THREAD

**Issue by NelTdS** [tgweber/fosc#5]
Seems like the newer version of tensorflow also breaks another interface: The input is expected to be in a correct order. For a quick work around, the vectorized input can be sorted in-place with ```vectorized.sort_indices()```. This should be considered to be integrated.

**Comment by tgweber** [comment]
Should be fixed see https://github.com/tgweber/fosc/blob/1e774dbdabf989c3f45c6f72ea08ee02fd40cf7a/fosc/__init__.py#L79
